name: 'Pull'

on:
  pull_request:
    branches:
      - main
      - canary
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft

concurrency:
  group: pull-${{ github.ref }}-1
  cancel-in-progress: true

env:
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  pull:
    name: 'CI'
    if: github.event.pull_request.draft == false &&
      !contains(github.event.head_commit.message, '[skip ci]')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      IS_ACTOR_VERIFIED: ${{ github.actor == 'ygorluiz' || github.actor == 'renovate[bot]' }}
      IS_ACTOR_YGORLUIZ: ${{ github.actor == 'ygorluiz' }}
      IS_ACTOR_DEPENDABOT: ${{ github.actor == 'dependabot[bot]' }}
      IS_ACTOR_RENOVATE: ${{ github.actor == 'renovate[bot]' }}
      IS_LABEL_PNPM: ${{ contains( github.event.pull_request.labels.*.name, 'pnpm' ) }}
    steps:
      - name: 'Checkout'
        id: pull-checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 10

      - name: 'Init'
        id: pull-init
        uses: YgorLuiz/monorepo/.github/actions/init@main

      # - name: 'ðŸ§ª debug'
      #   id: pull-debug
      #   shell: bash
      #   run: |
      #     echo 'IS_ACTOR_VERIFIED:   ${{ env.IS_ACTOR_VERIFIED }}'
      #     echo 'IS_ACTOR_YGORLUIZ: ${{ env.IS_ACTOR_YGORLUIZ }}'
      #     echo 'IS_ACTOR_RENOVATE:   ${{ env.IS_ACTOR_RENOVATE }}'
      #     echo 'IS_LABEL_PNPM:       ${{ env.IS_LABEL_PNPM }}'
      #     echo 'github.actor:        ${{ github.actor }}'

      # - name: 'ðŸ§ª debug ii'
      #   id: pull-debug-ii
      #   if: ${{ env.IS_ACTOR_VERIFIED == 'true' }}
      #   shell: bash
      #   run: |
      #     echo 'Note: true is a string ðŸ˜‘'

      # - name: 'ðŸ§ª debug iii'
      #   id: pull-debug-iii
      #   if: ${{ env.IS_ACTOR_RENOVATE == 'true' || env.IS_LABEL_PNPM == 'true' }}
      #   shell: bash
      #   run: |
      #     echo 'Note: This _would_ run the pnpm check'

      #  NOTE: Turn this off until determine if renovate handles this
      # - name: 'ðŸ”’  pnpm'
      #   id: pull-pnpm
      #   uses: YgorLuiz/monorepo/.github/actions/pnpm@main
      #   if: ${{ env.IS_ACTOR_RENOVATE == 'true' || env.IS_LABEL_PNPM == 'true' }}
      #   with:
      #     IS_ACTOR_VERIFIED: ${{ env.IS_ACTOR_VERIFIED }}
      #     IS_ACTOR_YGORLUIZ: ${{ env.IS_ACTOR_YGORLUIZ }}
      #     IS_ACTOR_DEPENDABOT: ${{ env.IS_ACTOR_DEPENDABOT }}
      #     IS_ACTOR_RENOVATE: ${{ env.IS_ACTOR_RENOVATE }}
      #     IS_LABEL_PNPM: ${{ env.IS_LABEL_PNPM }}

      - name: 'Install'
        id: pull-install
        uses: YgorLuiz/monorepo/.github/actions/install@main

      - name: 'Turbo Cache'
        id: pull-cache-turbo
        uses: YgorLuiz/monorepo/.github/actions/cache-turbo@main
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: 'Lint'
        id: pull-lint
        uses: YgorLuiz/monorepo/.github/actions/lint@main
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      # https://docs.github.com/en/actions/learn-github-actions/expressions
      - name: 'Commit Message'
        id: pull-commit-message
        run: |
          echo "::set-output name=message::$(git log --no-merges -1 --oneline)"

      - name: 'Build'
        id: pull-build
        uses: YgorLuiz/monorepo/.github/actions/build@main
        with:
          BUILD_COMMAND: 'build'
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: 'Deploy (Preview)'
        id: pull-deploy-preview
        if: ${{ (env.IS_ACTOR_VERIFIED == 'true') &&
          contains(steps.pull-commit-message.outputs.message, '[b]') }}
        uses: YgorLuiz/monorepo/.github/actions/deploy@main
        with:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PRODUCTION: false
          DEPLOY_PR_FROM_FORK: true
